AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda function EC2AppInstall

  Sample SAM Template to deploy EC2AppInstall application.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  EC2AppInstallFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  OneAllianceFunction:
    Description: "EC2AppInstallFunction Function ARN"
    Value: !GetAtt EC2AppInstallFunction.Arn
  OneAllianceFunctionIamRole:
    Description: "Implicit IAM Role created for EC2AppInstallFunction function"
    Value: !GetAtt EC2AppInstallFunction.Arn
